# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20170927_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailroomsview',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
